/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphsGraphIdRouteImport } from './routes/graphs/$graphId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as GraphsGraphIdIndexRouteImport } from './routes/graphs/$graphId/index'
import { Route as GraphsGraphIdViewRouteImport } from './routes/graphs/$graphId/view'
import { Route as GraphsGraphIdSettingsRouteImport } from './routes/graphs/$graphId/settings'
import { Route as GraphsGraphIdNodesNodeTypeSlugRouteImport } from './routes/graphs/$graphId/nodes/$nodeTypeSlug'
import { Route as GraphsGraphIdEdgesEdgeTypeSlugRouteImport } from './routes/graphs/$graphId/edges/$edgeTypeSlug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdRoute = GraphsGraphIdRouteImport.update({
  id: '/graphs/$graphId',
  path: '/graphs/$graphId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdIndexRoute = GraphsGraphIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GraphsGraphIdRoute,
} as any)
const GraphsGraphIdViewRoute = GraphsGraphIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => GraphsGraphIdRoute,
} as any)
const GraphsGraphIdSettingsRoute = GraphsGraphIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GraphsGraphIdRoute,
} as any)
const GraphsGraphIdNodesNodeTypeSlugRoute =
  GraphsGraphIdNodesNodeTypeSlugRouteImport.update({
    id: '/nodes/$nodeTypeSlug',
    path: '/nodes/$nodeTypeSlug',
    getParentRoute: () => GraphsGraphIdRoute,
  } as any)
const GraphsGraphIdEdgesEdgeTypeSlugRoute =
  GraphsGraphIdEdgesEdgeTypeSlugRouteImport.update({
    id: '/edges/$edgeTypeSlug',
    path: '/edges/$edgeTypeSlug',
    getParentRoute: () => GraphsGraphIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/graphs/$graphId': typeof GraphsGraphIdRouteWithChildren
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/view': typeof GraphsGraphIdViewRoute
  '/graphs/$graphId/': typeof GraphsGraphIdIndexRoute
  '/graphs/$graphId/edges/$edgeTypeSlug': typeof GraphsGraphIdEdgesEdgeTypeSlugRoute
  '/graphs/$graphId/nodes/$nodeTypeSlug': typeof GraphsGraphIdNodesNodeTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/view': typeof GraphsGraphIdViewRoute
  '/graphs/$graphId': typeof GraphsGraphIdIndexRoute
  '/graphs/$graphId/edges/$edgeTypeSlug': typeof GraphsGraphIdEdgesEdgeTypeSlugRoute
  '/graphs/$graphId/nodes/$nodeTypeSlug': typeof GraphsGraphIdNodesNodeTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/graphs/$graphId': typeof GraphsGraphIdRouteWithChildren
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/view': typeof GraphsGraphIdViewRoute
  '/graphs/$graphId/': typeof GraphsGraphIdIndexRoute
  '/graphs/$graphId/edges/$edgeTypeSlug': typeof GraphsGraphIdEdgesEdgeTypeSlugRoute
  '/graphs/$graphId/nodes/$nodeTypeSlug': typeof GraphsGraphIdNodesNodeTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/auth/signin'
    | '/graphs/$graphId'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/view'
    | '/graphs/$graphId/'
    | '/graphs/$graphId/edges/$edgeTypeSlug'
    | '/graphs/$graphId/nodes/$nodeTypeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/auth/signin'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/view'
    | '/graphs/$graphId'
    | '/graphs/$graphId/edges/$edgeTypeSlug'
    | '/graphs/$graphId/nodes/$nodeTypeSlug'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/auth/signin'
    | '/graphs/$graphId'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/view'
    | '/graphs/$graphId/'
    | '/graphs/$graphId/edges/$edgeTypeSlug'
    | '/graphs/$graphId/nodes/$nodeTypeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSigninRoute: typeof AuthSigninRoute
  GraphsGraphIdRoute: typeof GraphsGraphIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId': {
      id: '/graphs/$graphId'
      path: '/graphs/$graphId'
      fullPath: '/graphs/$graphId'
      preLoaderRoute: typeof GraphsGraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId/': {
      id: '/graphs/$graphId/'
      path: '/'
      fullPath: '/graphs/$graphId/'
      preLoaderRoute: typeof GraphsGraphIdIndexRouteImport
      parentRoute: typeof GraphsGraphIdRoute
    }
    '/graphs/$graphId/view': {
      id: '/graphs/$graphId/view'
      path: '/view'
      fullPath: '/graphs/$graphId/view'
      preLoaderRoute: typeof GraphsGraphIdViewRouteImport
      parentRoute: typeof GraphsGraphIdRoute
    }
    '/graphs/$graphId/settings': {
      id: '/graphs/$graphId/settings'
      path: '/settings'
      fullPath: '/graphs/$graphId/settings'
      preLoaderRoute: typeof GraphsGraphIdSettingsRouteImport
      parentRoute: typeof GraphsGraphIdRoute
    }
    '/graphs/$graphId/nodes/$nodeTypeSlug': {
      id: '/graphs/$graphId/nodes/$nodeTypeSlug'
      path: '/nodes/$nodeTypeSlug'
      fullPath: '/graphs/$graphId/nodes/$nodeTypeSlug'
      preLoaderRoute: typeof GraphsGraphIdNodesNodeTypeSlugRouteImport
      parentRoute: typeof GraphsGraphIdRoute
    }
    '/graphs/$graphId/edges/$edgeTypeSlug': {
      id: '/graphs/$graphId/edges/$edgeTypeSlug'
      path: '/edges/$edgeTypeSlug'
      fullPath: '/graphs/$graphId/edges/$edgeTypeSlug'
      preLoaderRoute: typeof GraphsGraphIdEdgesEdgeTypeSlugRouteImport
      parentRoute: typeof GraphsGraphIdRoute
    }
  }
}

interface GraphsGraphIdRouteChildren {
  GraphsGraphIdSettingsRoute: typeof GraphsGraphIdSettingsRoute
  GraphsGraphIdViewRoute: typeof GraphsGraphIdViewRoute
  GraphsGraphIdIndexRoute: typeof GraphsGraphIdIndexRoute
  GraphsGraphIdEdgesEdgeTypeSlugRoute: typeof GraphsGraphIdEdgesEdgeTypeSlugRoute
  GraphsGraphIdNodesNodeTypeSlugRoute: typeof GraphsGraphIdNodesNodeTypeSlugRoute
}

const GraphsGraphIdRouteChildren: GraphsGraphIdRouteChildren = {
  GraphsGraphIdSettingsRoute: GraphsGraphIdSettingsRoute,
  GraphsGraphIdViewRoute: GraphsGraphIdViewRoute,
  GraphsGraphIdIndexRoute: GraphsGraphIdIndexRoute,
  GraphsGraphIdEdgesEdgeTypeSlugRoute: GraphsGraphIdEdgesEdgeTypeSlugRoute,
  GraphsGraphIdNodesNodeTypeSlugRoute: GraphsGraphIdNodesNodeTypeSlugRoute,
}

const GraphsGraphIdRouteWithChildren = GraphsGraphIdRoute._addFileChildren(
  GraphsGraphIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSigninRoute: AuthSigninRoute,
  GraphsGraphIdRoute: GraphsGraphIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
